# Generated by Django 5.2.17 on 2026-08-15 16:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(max_length=12)),
                ('first_names', models.CharField(max_length=100)),
                ('last_names', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=20)),
                ('license_category', models.CharField(default='A-IIIc', max_length=10)),
                ('license_expiry', models.DateField()),
                ('medical_expiry', models.DateField(blank=True, null=True)),
                ('mining_experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('OBSERVED', 'Observado'), ('BLOCKED', 'Bloqueado')], default='ACTIVE', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='core.company')),
            ],
            options={
                'ordering': ('last_names', 'first_names'),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]{6,8}$', 'Placa inválida')])),
                ('vin', models.CharField(max_length=17)),
                ('engine_number', models.CharField(blank=True, max_length=40)),
                ('brand', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('year', models.PositiveSmallIntegerField()),
                ('vehicle_type', models.CharField(default='Volquete', max_length=40)),
                ('availability', models.CharField(choices=[('OWNED', 'Propio'), ('LEASED', 'Arrendado'), ('THIRD_PARTY', 'Tercero')], default='OWNED', max_length=20)),
                ('owner_name', models.CharField(max_length=180)),
                ('tare_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gross_weight_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payload_kg', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('odometer_km', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('OBSERVED', 'Observado'), ('ELIGIBLE', 'Apto documental'), ('BLOCKED', 'Bloqueado'), ('MAINTENANCE', 'Mantenimiento')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.company')),
            ],
            options={
                'ordering': ('plate',),
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('authorized_by', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('PROPERTY', 'Tarjeta de identificación vehicular'), ('SUNARP', 'Consulta/partida SUNARP'), ('CITV', 'CITV'), ('SOAT', 'SOAT'), ('INSURANCE', 'Seguro complementario'), ('MODIFICATION', 'Certificado de modificación'), ('OTHER', 'Otro')], max_length=20)),
                ('number', models.CharField(blank=True, max_length=80)),
                ('issuer', models.CharField(blank=True, max_length=120)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verification_level', models.CharField(choices=[('DECLARED', 'Declarado'), ('DOCUMENTED', 'Documentado'), ('VERIFIED', 'Verificado manualmente')], default='DECLARED', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('VALID', 'Vigente'), ('EXPIRING', 'Por vencer'), ('EXPIRED', 'Vencido'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('is_blocking', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, upload_to='vehicle_documents/%Y/%m/')),
                ('source_reference', models.CharField(blank=True, max_length=250)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle')),
            ],
            options={
                'ordering': ('expiry_date', 'document_type'),
            },
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(fields=('company', 'document_number'), name='unique_driver_document_per_company'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(fields=('company', 'license_number'), name='unique_license_per_company'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('company', 'plate'), name='unique_plate_per_company'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('company', 'vin'), name='unique_vin_per_company'),
        ),
    ]
