# Generated by Django 5.2.17 on 2026-08-15 16:55

import django.core.validators
import django.db.models.deletion
import fleet.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_type', models.CharField(choices=[('INDUCTION', 'Inducción minera'), ('DEFENSIVE', 'Manejo defensivo'), ('FIRST_AID', 'Primeros auxilios'), ('INTERNAL_AUTH', 'Autorización interna'), ('COMPETENCY', 'Competencia por equipo')], max_length=30)),
                ('number', models.CharField(blank=True, max_length=80)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verification_level', models.CharField(choices=[('DECLARED', 'Declarado'), ('DOCUMENTED', 'Documentado'), ('VERIFIED', 'Verificado manualmente')], default='DECLARED', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('VALID', 'Vigente'), ('EXPIRED', 'Vencido'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('file', models.FileField(blank=True, upload_to='driver_credentials/%Y/%m/', validators=[fleet.validators.validate_evidence_file])),
                ('sha256', models.CharField(blank=True, editable=False, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequirementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('subject', models.CharField(choices=[('VEHICLE', 'Vehículo'), ('DRIVER', 'Conductor')], max_length=20)),
                ('evidence_type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('blocking', models.BooleanField(default=True)),
                ('minimum_verification', models.CharField(choices=[('DECLARED', 'Declarado'), ('DOCUMENTED', 'Documentado'), ('VERIFIED', 'Verificado manualmente')], default='DOCUMENTED', max_length=20)),
                ('legal_or_client_source', models.CharField(max_length=250)),
                ('source_version', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('subject', 'code'),
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='operational_status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('MAINTENANCE', 'Mantenimiento'), ('OUT_OF_SERVICE', 'Fuera de servicio')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vehicle_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='sha256',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_vehicle_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{3}-?[A-Z0-9]{3,4}$', 'Placa inválida')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('OBSERVED', 'Observado'), ('ELIGIBLE', 'Apto documental'), ('BLOCKED', 'Bloqueado'), ('MAINTENANCE', 'Mantenimiento')], default='DRAFT', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator('^[A-HJ-NPR-Z0-9]{17}$', 'VIN inválido: debe tener 17 caracteres y no usar I, O o Q.')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='file',
            field=models.FileField(blank=True, upload_to='vehicle_documents/%Y/%m/', validators=[fleet.validators.validate_evidence_file]),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('operation', models.CharField(blank=True, max_length=160)),
                ('source', models.CharField(blank=True, max_length=250)),
                ('source_version', models.CharField(blank=True, max_length=40)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('reviewed_at', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('disclaimer', models.TextField(default='Perfil referencial sujeto a validación contra bases y documentos oficiales vigentes.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_profiles', to='core.company')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='client_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='fleet.clientprofile'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='client_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet.clientprofile'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('gross_weight_kg__gte', models.F('tare_kg'))), name='gross_weight_gte_tare'),
        ),
        migrations.AddField(
            model_name='drivercredential',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='requirementrule',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='fleet.clientprofile'),
        ),
        migrations.AddConstraint(
            model_name='clientprofile',
            constraint=models.UniqueConstraint(fields=('company', 'name', 'operation'), name='unique_client_operation'),
        ),
        migrations.AddConstraint(
            model_name='requirementrule',
            constraint=models.UniqueConstraint(fields=('client_profile', 'code'), name='unique_requirement_code_per_profile'),
        ),
    ]
